---
title: "Введение в Linux"
author: "Алексей Гуревич, Андрей Пржибельский"
output:
  html_document: 
    highlight: textmate
  pdf_document: default
header-includes: \usepackage[english, russian]{babel}
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

# 1. Введение
## 1.1 Общая информация о курсе

## 1.2 Как установить Linux

## 1.3 Осваиваем Linux

## 1.4 Terminal: основы
### 1.4.1 План урока
Мы привыкли работать на компьютере, кликая с помощью мышки на иконки и выбирая пункты в различных меню. Однако есть и другой подход, который позволяет отдавать команды компьютеру, вводя их с помощью клавиатуры в специальную программу **Terminal**. Поначалу это будет непривычно и, возможно, даже неудобно, но вскоре мы поймем преимущество именно такого подхода.

На этом занятии мы научимся запускать **Terminal**, а также изучим несколько базовых команд для работы в нём. Показанные на занятии слайды доступны по [ссылке](https://stepik.org/media/attachments/slides/course73/lec1_frag3.pdf).

Важно отметить, что, если вы используете Mac OS X, то терминал у вас тоже есть! Можете ввести в поиск Terminal и запустить его. Большинство команд терминала, которые мы изучим, будут работать одинаково как в Mac OS X, так и в Linux, однако эти две программы не абсолютно одинаковы, и незначительные различия всё-таки могут встретиться.

Пользователи Windows могут работать в Linux-подобном терминале с использованием среды [Cygwin](https://www.cygwin.com/). Она не является полноценной виртуальной системой c Linux, как VirtualBox, которую мы устанавливали на первом занятии, однако Cygwin позволит освоить терминал и выполнить практически все задачи из нашего курса. Для установки среды на свой компьютер зайдите на [страницу установки](https://cygwin.com/install.html), скачайте подходящую вашей системе установочную программу и запустите её. В процессе установки вы можете выбрать все значения по умолчанию. После успешного завершения установки Cygwin станет доступен из меню Пуск.

### 1.4.2 Запускаем терминал
В **ubuntu** для открытия эмулятора теминала необхожимо нажать сочетание клавиш `Ctrl`+`Alt`+`T`

Чтобы узнать какой командный интерпретатор используется на системе, можно выполнить например такую команду (`eugene` - текущее имя пользователя):
```{bash}
grep "eugene:" /etc/passwd
```

### 1.4.3 Задача
Выберите все синонимы для “командной строки”.

#### Ответы:

* **Терминал**
* Ассоль
* Термин
* **Консоль**

#### Комментарий [Сергея Федорова](https://stepik.org/users/34970986)
Cтрого говоря, консоль, терминал и командная строка -- изначально разные понятия, которые сейчас используются как синонимы устройств ввода-вывода. Консоль, чтобы проще это то, что было до графического интерфейса, сейчас -- работа с компьютером без графического интерфейса.

Нажмите `Ctrl`+`Alt`+`F1` (`F2`,...) и вы окажетесь в **консоли**, но никак не в терминале. Нажмите, находясь в консоли, на `Alt`+`F7` -- вы окажетесь в графическом режиме. Мы говорим, переключаться между консолями, или консолью и графическим режимом. Но не переключиться между терминалами.

**Terminal**, который здесь запускается - это **симулятор консоли**. т.е программа, запущенная в графическом режиме, симулирующая консоль, т.е. неграфический режим. В отличие от удаленного терминала (монитора и клавиатуры), через который сообщаются с компьютером, и которых может быть много, программу **terminal** еще называют графическим терминалом. Терминал - это программа взаимодействия с компьютером в текстовом режиме с помощью команд.

Конечно, в русском языке это на называют командной строкой. Но по факту в терминале реализован интерфейс командной строки, т.е. способ общения с компьютером с помощью команд. Пользователь вводит в терминал команду, а командный интерпретатор линукс их уже выполняет.

### 1.4.4 Знакомство с командами терминала
**pwd** (**p**rint **w**orking **d**irectory) -- выводит директорию, где мы сейчас находимся

**ls** (**l**i**s**t directory content) -- выводит содержимое директории

Сочетание клавиш `Ctrl`+`L` очистит окно терминала (точнее создаст как бы чистый экран после уже введенных команд и их выводов, т.о. ранее введенные команды не стираются).

**ВАЖНО** -- терминал чувствителен к регистру

### 1.4.5 Задача
Какая команда напечатает в какой директории мы сейчас находимся?

#### Ответы:

* pwd или PWD, но не Pwd
* **Только pwd**
* Только Pwd 

### 1.4.6 Общий вид комманды для терминала
В общем случае команда принмает вид:

**команда** **опции** ***аргументы*** 

Например команда `ls` может быть записана следующим образом:
```{bash}
ls --all --human-readable -l ~/Загрузки/
```

Если не задавать путь (~/Загрузки/ в данном случае), то команда выведет содержимое текущей директории. А если он задан, то содержимое, которое мы указали. 

Опции:

* `-l` -- преобразует вывод в список, давая много дополнительной информации
* `--human-readable` -- выводит размер файлов в читаемом виде (по-умолчанию размер выводится в байтах)
* `--all` -- выводит все скрытые файлы в директории; **все скрытые файлы и папки начинаются с точки**

Заметим, что у однобуквенных опций стоит один минус, а у опций длинной больше одной буквы  -- два минуса! 

Вводить такие опции довольно долго, поэтому в линуксе почти у всех команд есть как длинные версии опций, так и короткие, состоящие всего из одной буквы. Например эту команду можно записать гораздо короче:
```{bash}
ls -a -h -l ~/Загрузки/
```

Но еще укоротить запись можно слив все опции под один знак минуса (чтобы отличить путь от опций):
```{bash}
ls -ahl ~/Загрузки/
```

Внутри этой записи порядок опций произвольный (в некоторых других командах порядок опций важен), поэтому такая запись валидна и выдаст тот же результат:
```{bash}
ls -lah ~/Загрузки/
```

У команд обычно довольно много опций, чтобы посмотреть их все, нужно открыть **man**ual этой команды:
```{bash}
man ls
```

Для выхода из режима справки, необходимо нажать букву **Q**.

#### Еще пара команд полезных команд
Команда `clear` -- очистит экран

Команда `exit` -- закроет терминал

### 1.4.7 Задача
Укажите, какие из следующих команд полностью эквивалентны команде `ls -A --human-readable -l /some/directory`

#### Ответы

* ls -A --human-readable -l
* **ls -h -A -l /some/directory**
* **ls -Ahl /some/directory**
* **ls -lAh /some/directory**
* **ls --human-readable -A  -l /some/directory**

### 1.4.8 Пара советов по вводу команд в терминале
Если мы уже ввели несколько команд в терминал, то перемещаться по этой истории можно при помощи стрелок **вверх** и **вниз** на клавиатуре. Терминал помнит команды, которые вводились до его закрытия. 

Для перемещения внутри команды, использутся стрелки **влево** и **вправо** на клавиатуре.

#### Сочетания клавиш

* `ctrl`+`a` -- перемещение курсора в начало строки
* `ctrl`+`e` -- перемещение курсора в конец строки
* `alt`+`b` -- перемещение курсора в начало предыдущего слова
* `alt`+`b` -- перемещение курсора в начало последующего слова

Вот [здесь](https://ss64.com/bash/syntax-keyboard.html) список сочетаний клавишь побольше.

Двойное нажатие `Tab`+`Tab` после ввода части команды выведет все возможные варианты. 

### 1.4.9 Различные виды путей
В линуксе, если мы будем подниматься вверх по директориям, то в конце концов дойдем до **корневой директории**. 

Она обозначается знаком `/`

Отсюда следует два варианта написания пути:

* **Абсолютный путь** -- путь от корневой директории; всегда начинается с `/`
* **Относительный путь** -- путь от текущей директории; **БЕЗ** `/`

#### Специальные символы в путях

* `.` -- текущая директория 
* `..` -- директория на уровень выше
* `~` -- домашняя директория

Так же некоторые команды допускают использование сиволов:

* `*` -- любое количество любых символов
* `?` -- ровно один любой символ

### 1.4.10 Задача
Предположим, что вы находитесь в директории `/home/bi/Documents`, причем `/home/bi` — ваша домашняя директория. Какая(ие) команда выведет содержимое `/home/bi/Downloads`, при этом не показывая содержимое других директорий?

#### Ответы

* **ls /home/bi/Downloads**
* ls ./Downloads
* **ls ./../Downloads**
* ls Downloads 

### 1.4.11 Операции с файлами и директориями
#### Создание

* **mkdir *путь_до_директории*** -- создаст директорию

* **mkdir -p *путь_до_директории*** -- создаст директорию и ее "родителей"

* **touch *путь_до_файла*** -- создаст файл

* **cd *путь_до_директории*** -- войти в директорию; путь можно ввести как абсолютный, так и относительный.

#### Удаление
* **rm *путь_до_файла*** -- удалит файл

* **rm -r *путь_до_директории*** -- удалит директорию; r - recursive

* **rm -rf *путь_до_директории*** -- удалит директорию без доп вопросов; f - force

* **rm -rf *путь_до_директории/**** -- удалит все файлы в директории

#### Копирование и перемещение

* **cp *путь_до_файла1* *путь_до_файла2*** -- скопирует файл1 в файл2

* **cp -r *путь_до_дир1* *путь_до_дир2*** -- скопирует дир1 в дир2

* **mv *путь1* *путь2*** -- перемещение директории или файла

### 1.4.12 Задача
Какая команда используется для удаления директорий?

#### Ответы
* mkdir
* mv
* **rm -r**
* mkdir -r 

## 1.5 Запуск исполняемых файлов
### 1.5.1 План урока
На этом занятии мы научимся запускать программы из командной строки. Сделаем это как для уже установленных в системе приложений (например, Firefox), так и скачанных из интернета или написанных нами программ. Будут рассмотрены возможности прервать или приостановить запущенную программу, а также запустить сразу несколько приложений одновременно.

### 1.5.2 Запуск сторонних приложений
Терминал не ограничивается запуском встроенных команд. Из него можно запускать программы, установленные прямо в системе, и не имеющие никакого отношения к терминалу. Например *Firefox* или *gedit*.

Если в терминал ввести слово `gedit` то в отдельном окне откроется программа **Gedit**.

При открытом приложении из терминала любые команды, написанные в нем выполняться не будут.

Но как тольок мы закроем приложение **Gedit** (банально нажав на крестик), мы увидем, как выполнятся те набранные команды.

Такая связка рпаботает и в другую сторону: при попытке закрыть термнал (когда из него открыто какое-либо приложение) предупреждение, что из терминала запущено приложение. И закрыв терминал, вы закроете и приложение.

### 1.5.3 Задача
Что произойдет, если ввести в терминал команду `firefox` (для запуска одноименного браузера), а затем ввести туда же команду `exit`?

#### Ответы

* `Firefox` закроется, `Terminal` продолжит работу
* **Никто не закроется**
* Обе программы закроются
* `Terminal` закроется, `Firefox` продолжит работу 

### 1.5.4 Закрытите сторонних приложений
Сочетания клавиш:

* `ctrl`+`c` (`ctrl`+`shift`+`c`) -- прерывает выполнение программы
* `ctrl`+`z` -- приостанавливает выполнение программы

При приостановке программы ее можно продолжить или прододлжить в фоновом режиме:

* **fg** -- продолжить (foreground)
* **bg** -- продолжить в фоновом режиме (background)

Отличие между прерываниями крестиком и `ctrl`+`c` в том, что при втором варианте закрытия команды введенные при работающем приложении не будут выполнены (прервется не только сама программа, но и все что было написано в терминале пока она работала).

### 1.5.5 Запуск программ из произвольной директории

Запуск файла `.py` -- поставить перед названием файла `./`

Пара слов о `chmod`

Позже надо поподробнее рсписать.

### 1.5.6 Задача
Чему эквивалентен запуск программы с &?

#### Ответы

* Запуск, Ctrl+Z
* **Запуск, Ctrl+Z, bg**
* Запуск, Ctrl+C, fg
* Запуск, Ctrl+C, bg 

### 1.5.7 Задача
Скачайте [файл](https://stepik.org/media/attachments/course73/lec1_frag4_current_time.py) с программой, сделайте его исполняемым, запустите и скопируйте то, что он выведет на экран, в форму ниже.

#### Решение
```{bash}
wget https://stepik.org/media/attachments/course73/lec1_frag4_current_time.py
chmod +x lec1_frag4_current_time.py
./lec1_frag4_current_time.py
```

## 1.6 Ввод/вывод
### 1.6.1 План урока
Большинство программ, запущенных в терминале, активно взаимодействует с пользователем: они требуют от него некоторые данные на вход, сообщая результаты своей работы на выходе. Чаще всего для ввода данных используется клавиатура, а результаты выводятся на экран. Однако это не всегда может быть удобно. Мы научимся передавать приложению входные данные не с клавиатуры, а из файла, а также записывать (перенаправлять) результаты его выполнения и возникшие при этом ошибки не на экран, а в файл или несколько файлов.

### 1.6.2 Просмотрщики и редакторы файлов
#### Просмотровщики `cat`, `head`, `tail` 
Базовый просмотровщик, выводит на экран содержимое файла.

**cat *файл***

После этого сразу можно продолжить рааботать в терминале. 

`cat` -- выводит содержимое файловпо очереди, как бы соединяет их -- конкатенирует (concatinate), отсюда и название. Например вывести всего Пушкина `cat pushkin1.txt pushkin2.txt | less`.

* `tac` -- файл задом на перед
* `head` -- первый 10 строк файла
* `tail` -- первый 10 строк файла

#### Просмотровщик `less`
Он более продвинут, открывает файл в собственном окне.

**less *файл***

* `q` -- выход из режима просмотра
* `/` -- поиск
* `g` -- в начало
* `G` -- в конец

#### Редактор `nano`
Просмотровщики не позволяют редактировать файлы, для этого необходимы рдакторы.

**nano *файл***

Список команд расписан внизу редактора.

### 1.6.3 Standart input, output and error
Программа принимает данные на вход -- `stdin` (keyboard). Далее она может обработать эти данные и выдать на выходе либо обычный `stdout` (screen) либо ошибочный `stderr` (screen). По умолчанию оба вывода выводятся на экран, и нам сложно отличить сообщение об ошибке от обычного сообщения. 

Но преимеществом терминала является возможность эти умолчания поменять. И выводить информацию не на экран, а в файл. Либо считывать не с клавиатуры, а из файла.

Это называется перенаправлением вывода или ввода. 

* **Программа < файл** -- чтобы брать `stdin` из файла
* **Программа > файл** -- чтобы выводить `stdout` в файл
* **Программа >> файл** -- аналогично, но с дозаписью в файл
* **Программа 2> файл** -- чтобы выводить `stderr` в файл
* **Программа 2>> файл** -- аналогично, но с дозаписью в файл

#### Перенаправление в действии
Программа `interacter.py` взаимодействует с пользователем: она справшивает имя пользователя и здоровается с ним. Если сделать ошибку в имени, т.е. написать его с маленькой буквы, то программа предупредит об этом и поздоровается с исправленной версией имени. Если ничег оне вводить, то программа попрощается с нами.

Вот сама программа:
```{python}
#!/usr/bin/python

import sys

while True:
    print("Hi, what is your name?")
    line = sys.stdin.readline()
    line = line.strip()
    if not line:
        print("Bye!")
        break
    if line[0].islower():
        sys.stderr.write("You made a mistake! I will capitalize your name!\n")
    print("Nice to meet you, " + line[0].upper() + line[1:] + "!")
```

Итак, мы видими, что программа принимает на вход некую информацию с клавиатуры. В данном случае это были имена. И выводит что-то на экран. На самом деле на экран выводился не только `stdout` но и `stderr`, это были выводы с ошибками. Но чтобы узнать это, нам нужно воспользоваться перенаправлением.

Двавайте перенаправим вывод программы в два файла:
```{bash}
./iteractor.py >out.txt 2>err.txt 
```

На экран уже не будут выводиться результаты, весь вывод будет уходить в два файла `out.txt` и `err.txt`, но ввод все еще остался с клавиатуры.

Мы смогли разделить два потока `stdout` но и `stderr`!

Но так же мы можем передавать список имен в `stdin` из файла.

Давайте при помощи редактора `nano` создадим файл `names.txt`, и поместим туда имена. 
```
Misha
Alexsey
nikolay
```

Допишем нашу команду:
```{bash}
./iteractor.py >out.txt 2>err.txt <names.txt
```

Программа отработала, мы не видели никакого взаимодействия, но если теперь посмотреть содержимое файлов, то увидим, что оно поменялось.
```{bash}
cat out.txt
cat err.txt
cat names.txt
```

#### Примечание от [Bakharev Andrey](https://stepik.org/users/192251)
Наверное нужно добавить, что если необходимо ошибки писать в тоже место, что и вывод, то вместо дублирования файла, лучше использовать конструкцию `2>&1`, т.е. например так:

`./run_task.py 1>/var/log/my_program/log 2>&1`

Тогда и вывод, и ошибки будут отправляться в файл  `/var/log/my_program/log`.

Когда же нас вывод вообще не интересует, то весь вывод (в том числе ошибки) можно перенаправлять в "черную дыру" -- `/dev/null`.

#### Примечание от [Nikita Makarenko](https://stepik.org/users/164735)
Возможно стоило отдельно обратить внимание на [tee](https://ru.wikipedia.org/wiki/Tee) как на воможность и писать поток на экран и одновременно  записывать его в файл. 

### 1.6.4 Задача
Куда по умолчанию выводится поток ошибок из программы, запущенной в терминале?

* Никуда
* В файл err.txt
* **На экран**
* В файл stderr 

### 1.6.5 Задача
Какие (какая) из команд создадут файл `file.txt` и запишут в него поток ошибок программы `program`? Считайте, что в момент запуска программы файл `file.txt` не существует.

* program << file.txt
* program < file.txt
* program file.txt <2
* **program 2> file.txt**
* **program 2>> file.txt**
* program >> file.txt

### 1.6.6 Конвеер `pipe`
Конвеер -- объединение нескольких программ в одну большую цепочку, где каждая последующая программа берет на вход вывод предыдущей программы.

**Прогр1 | Прогр2 | ... | ПрогрN**

После нажатия на энтер, запустится процесс выполнения; и пока первая программа не выполнится, вторая не получит данные на вход.

```{bash}
cat new_names.txt | ./interacter.py | cat
```

### 1.6.7 Задача
Куда деваются сообщения об ошибках (т.е. вывод в stderr) от тех программ, которые объединены в конвейер (pipe)?

#### Ответ

* Записываются в файл pipe.err
* Исчезают (никуда не выводятся)
* **Выводятся на экран**

## 1.7 Скачивание файлов из интернета
### 1.7.1 План урока
Скачивать файлы из интернета можно не только через браузер, но и через терминал. На этом занятии мы научимся это делать при помощи команды `wget`. Эта программа очень многофункциональна, но мы рассмотрим только основные её возможности. Однако для прохождения всех тестовых заданий вам нужно будет посмотреть справку по wget, чтобы ознакомиться с этой программой подробнее!

### 1.7.2 Команда `wget`
В простейшем виде синтаксис команды выглядит таким образом:

**wget *ссылка*** -- скачать файл по *ссылке* и сохранить в текущей директории.

Если мы хотим скачать файл в другую директорию, то нужно добавить опцию `-P`:

**wget -P *путь_до_директори ссылка*** -- скачать файл по *ссылке* и сохранить в директории заданной *путем*

Если мы хотим принцпиально заменить имя файла, то добавляем опцию `-O`:

**wget -O *путь_до_файла ссылка*** -- скачать файл по *ссылке* и сохранить в директории  с именем заданной *именем*

### 1.7.3 Задача
В каком файле на диске окажется картинка, если для её скачивания были выполнены следующие команды?

```{bash}
cd /home/alex/
wget -P /home/alex/Pictures -O 1.jpg http://example.com/example.jpg
```

#### Ответ

* /home/alex/Pictures/1.jpg
* /home/alex/example.jpg
* **/home/alex/1.jpg**
* /home/alex/Pictures/example.jpg

Префикс `-О` заслоняет `-Р`

### 1.7.4 Пара полезных опций команды `wget`
Докачать файл с помощью префикса `-c`:

**wget -c *ссылка*** -- докачать файл по *ссылке* при обрыве связи

Проверка правильности ссылки с помощью префикса `--spider`:

**wget - -spider *ссылка*** -- *проверить* доступность файла по *ссылке*

Если ссылок много, то лучше записат ьих в текстовый файл и передать в `wget` при помощи префикса `-i`:

**wget -i *текстовый_файл*** -- скачать несколько файлов по ссылкам из текстового файла

### 1.7.5 Задача
Какую опцию нужно указать команде `wget`, чтобы она не выводила никаких сообщений на экран (Resolving.., Connecting to.. и т.д.)?

#### Ответы

* -v или --verbose
* -nv или --no-verbose
* **-q или --quiet**

### 1.7.6 Еще несколько подходов использования `wget`
Управляем глубиной скачивания с помощью префиксов `-r` и `-l`:

**wget -r -l *глубина ссылка*** -- *рекурсивное* скачивание файлов по *ссылке* на указанную *глубину* (по умолчанию глубина 5)

### 1.7.7 Задача
Пусть на некоторой web-странице есть ссылки на картинки в форматах png и jpg, а также ссылки на другие страницы сайта (обычные html файлы). Какие файлы будут скачаны на компьютер, если запустить `wget -r -l 1 -A jpg` и передать в качестве аргумента ссылку на эту web-страницу? Выберите наиболее полный ответ!

#### Ответы

* Будут скачаны только картинки (jpg и png), но все png будут удалены
* Не будет скачано ничего
* Будут скачаны только картинки (png и jpg), html скачиваться не будут
* Не будет скачено ни jpg, ни png картинок, только html файлы
* Будут скачаны только png файлы
* **Будут скачаны jpg и html файлы, но все html будут удалены**

## 1.8 Работа с архивами
### 1.8.1 План урока
Иногда нам нужно передать по почте или скачать из интернета очень большой файл. Или на нашем жестком диске заканчивается место и хочется, чтобы некоторые файлы занимали поменьше пространства. В этом случае нам на помощь могут прийти специальные программы — архиваторы. Они позволяют записывать хранящуюся в файлах информацию в более компактном виде, т. е. уменьшить их размер без потери информации. Обработанные архиватором данные (файлы и папки) помещаются в файл, который называется архив, а сам процесс обработки называется архивированием (сжатием, запаковыванием). Размер архива зависит от того, какая информация была в исходных данных: например, тексты сжимаются очень хорошо (архив может иметь размер в десятки раз меньше, чем исходный файл), а видео-файлы почти не сжимаются.

На этом занятии мы познакомимся с несколькими архиваторами и научимся работать с ними в терминале: будем как создавать архивы, так и распаковывать их, т. е. получать из архива исходные файлы и папки.




