---
title: "ОЭС-2"
author: "Евгений Михейкин"
date: "18 10 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(openxlsx)
```

### Функция чтения списка файлов
```{r}
path_f <- function(path, pattern) {
 path_file <- dir(path,             # путь к папке, каждый раз будет свой 
                  pattern,          # выбираем файлы только по паттерну 
                  recursive = T,    # рекурсивно по всем папкам
                  include.dirs = T,    
                  full.names = T)   # вывод полного пути
 return(path_file)                  # возвращаемое из функции значение
}
```

### Чтение списка файлов
```{r}
path_file <- path_f("~/Desktop/OES_input", "\\.xlsx?$")
cat("Количество файлов в папке Input: ")

path_file %>% 
  length() %>% 
  cat("\n")
head(path_file)

cat("Количество файлов в папке Output: ")

path_f("~/Desktop/OES_output/", "\\.xlsx?$") %>% 
  length() %>% 
  cat("\n")
```

### Переименовка файлов
```{r}
# Функция раз
funfun <- function(path, sheet) { 
 # path <- "/Users/macmini/Desktop/OES_input/Лист184.xlsx"
 # sheet <- 1
  df <- read_excel(path, sheet, range = "A1:A10", col_names = F)
 vec <- as.vector(df$X__1)
 
 A <- grepl("^С", vec[2])
 B <- grepl("^А", vec[8])
 
 ifelse(A & !B, vec[2], vec[8]) %>%
   gsub(pattern = "/", replacement = "-") #%>%
   # gsub(pattern = "\\s+", replacement = "_")
 
 # if (A & !B) {
 #   return(vec[2] %>% gsub(pattern = "/", replacement = "-"))
 # } else if (!A & B) {
 #   return(vec[8] %>% gsub(pattern = "/", replacement = "-"))
 # } else {
 #   return("Пустой файл")
 # }
 
 
}

# Функция два
funfunfun <- function(path_file) {
  file.copy(from = path_file, 
             to = paste0("~/Desktop/OES_output/",
                         path_file %>% funfun(1),
                         # "_", i,
                         ".xlsx"),
            overwrite = F)
}

system.time({
  path_file %>%
  map(funfunfun)
})
```

### Вытягивание информации из счет-фактур
```{r}
fun1 <- function(path) {
# path <- "/Users/macmini/Desktop/OES_input/СЧЕТ-ФАКТУРА № Э-281-06-7 от 30 июня 2016 г..xlsx"
 df <- read_excel(path, sheet = 1, cell_cols(1:13), col_names = F)
 df_out <- data_frame("Счет-фактура" = c(df$X__1[2]),
                      "Продавец" = c(df$X__1[4]) %>% gsub(pattern = "Продавец: ", replacement = ""),
                      "Адрес" = c(df$X__1[5]) %>% gsub(pattern = "Адрес: ", replacement = ""),
                      "ИНН/КПП" = c(df$X__1[6]) %>% gsub(pattern = "ИНН/КПП продавца: ", replacement = ""),
                      "Грузоотправитель и его адрес" = c(df$X__1[7]) %>% gsub(pattern = "Грузоотправитель и его адрес: ", replacement = ""),
                      "Грузополучатель и его адрес" = c(df$X__1[7]) %>% gsub(pattern = "Грузополучатель и его адрес: ", replacement = ""),
                      "К платежно-расчетному документу" = c(df$X__1[9]) %>% gsub(pattern = "К платежно-расчетному документу: ", replacement = ""),
                      "Покупатель" = c(df$X__1[10]) %>% gsub(pattern = "Покупатель: ", replacement = ""),
                      "Адрес2" = c(df$X__1[11]) %>% gsub(pattern = "Адрес: ", replacement = ""),
                      "ИНН/КПП покупателя" = c(df$X__1[12]) %>% gsub(pattern = "ИНН/КПП покупателя: ", replacement = ""),
                      # "Расчетный период" = c(df$X__1[13]) %>% gsub(pattern = "Расчетный период: ", replacement = ""),
                      "Всего к оплате" = c(df$X__13[nrow(df) - 7]),
                      "Договор" = c(df$X__1[14]) %>% gsub(pattern = "Договор ", replacement = "")
                      )
 return(df_out)
 
}

df_bill <- path_file %>% 
  map_df(fun1) 

write.xlsx(df_bill, file = "~/Desktop/OES_output/Реестр Счет-Фактур.xlsx", asTable = T)

```

### Вытягивание информации из актов
```{r}
fun2 <- function(path) {
  # path <- "/Users/macmini/Desktop/OES_input/Акт приема-передачи электрической энергии № Э-298-06-48 от 30 апреля 2016 г..xlsx"
 df <- read_excel(path, sheet = 1, cell_cols(1:19), col_names = F)
 df_out <- data_frame("Акт приема-передачи" = c(df$X__1[8]),
                      "ОЭС" = c(df$X__2[5]),
                      "Отделение ОЭС" = c(df$X__2[6]),
                      "Кому" = c(df$X__10[5]),
                      "Кому2" = c(df$X__10[6]),
                      "Расчетный период" = c(df$X__2[9]) %>% gsub(pattern = "Расчетный период: ", replacement = ""),
                      "Договор" = c(df$X__12[3]),
                      "Всего к оплате" = c(df$X__18[nrow(df) - 15])
                        )
 return(df_out)
}

df_act <- path_file %>% 
  map_df(fun2) 

write.xlsx(df_act, file = "~/Desktop/OES_output/Реестр Актов.xlsx", asTable = T)
```


