---
title: "Shiny Server Setup"
output:
  pdf_document: default
  html_document: default
header-includes: \usepackage[english, russian]{babel}
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = F)
```

## Установка Shiny Server (Open Source)
### Полезные ссылки
Основная страница с шагами по установке <https://www.rstudio.com/products/shiny/download-server/>.

Установка `R` на Ubuntu описана <https://cran.rstudio.com/bin/linux/ubuntu/README.html#installation>.

### Шаги установки

До установки Shiny Server'а необходимо установить сам язык `R` и пакеты `shiny`, `rmarkdown` (на всякий случай):
```{bash}
sudo apt-get install r-base
sudo su - \ -c "R -e \"install.packages('shiny', repos='https://cran.rstudio.com/')\""
sudo su - \ -c "R -e \"install.packages('rmarkdown', repos='https://cran.rstudio.com/')\""
```

После этого необходимо установить `gdebi`, с его помощью и будет уcтановлен `Shiny Server`:
```{bash}
sudo apt-get install gdebi-core
```

Устаналиваем `Shiny Server` (Version: 1.5.6.875  Released: 2017-10-23 ):
```{bash}
wget https://download3.rstudio.org/ubuntu-12.04/x86_64/shiny-server-1.5.6.875-amd64.deb
sudo gdebi shiny-server-1.5.6.875-amd64.deb
```

## Первые шаги
Полная документация лежит здесь <http://docs.rstudio.com/shiny-server/>.

### Включение, отключение и перезапуск сервера
```{bash}
sudo systemctl start shiny-server
sudo systemctl stop shiny-server
sudo systemctl restart shiny-server
```

### Статус сервера
```{bash}
sudo systemctl status shiny-server
```

### Старт сервера при загрузке системы (y/n)
```{bash}
sudo systemctl enable shiny-server
sudo systemctl disable shiny-server
```

## Что и где лежит
### Файл конфигурации shiny-server.conf
Файл с базовой кофигурацией лежит по адресу `/etc/shiny-server/shiny-server.conf` и представляет из себя обчно что-то такое:
```
# Instruct Shiny Server to run applications as the user "shiny"
run_as shiny;

# Define a server that listens on port 3838
server {
  listen 3838;

  # Define a location at the base URL
  location / {

    # Host the directory of Shiny Apps stored in this directory
    site_dir /srv/shiny-server;

    # Log all Shiny output to files in this directory
    log_dir /var/log/shiny-server;

    # When a user visits the base URL rather than a particular application,
    # an index of the applications available in this directory will be shown.
    directory_index on;
  }
}
```
Более подробное описание всех настроек и параметров этого файла можно найти  в Appendix'e <http://docs.rstudio.com/shiny-server/#appendix> Shiny Administrator’s Guide.


