---
title: "Эконометрика"
author: "Демешев Борис Борисович"
output:
  html_document: default
  pdf_document: default
header-includes: \usepackage[english, russian]{babel}
---
```{r setup, include = F}
library(knitr)    # нужен для ф-ии kable
library(ggplot2)
library(dplyr)    # для обработки данных
library(GGally)   # для матриц диаграмм рассеивания
library(psych)    # для описательных статистик
```

### 2.1.1. Условное математическое ожидание. Определение
Вторая неделя посвящена статистическим свойствам оценок коэффициентов.

* сформулируем стандартные предпосылки
* строить доверительные интервалы для коэфициентов
* проверять гипотезы о коэффициентах

Для того чтобы сформулировать стандартные предпосылки нам потребуется понятие **Условного математического ожидания**.

Рассмотрим это понятие на примере двух случайных величин $r$ и $s$. Мы хотим потстроить такую случайную величину, которая называется **Условным математическим ожиданием** $E(s|r)$ ($E$ от $s$ при условии $r$), которая по смыслу является наиболее похожей на $s$ случайно величиной выражающейся только через $r$.

Формально $E(s|r)$ - это случайная величина $\tilde s$.

С одной стороны $s$ с тильдой является функцией от $r$, а с другой она очень похожа на $s$. А именно мат ожидание от $\tilde s$ равно мат ожиданию от $s$: 
$$E(\tilde s)=E(s)$$

И ковариация между $s$ и любой функцией от $r$ равна ковариации между $\tilde s$  и той же самой функцией от $r$:
$$Cov(s,g(r))=Cov(\tilde s, g(r))$$
В простых случаях если величина $r$ дискретна и принимает значения $a$, $b$ или $c$, то:
$$
E(s|r)=
\left\{
  \begin{aligned}
    &E(s|r=a), \text{ если } r=a \\
    &E(s|r=b), \text{ если } r=b \\
    &E(s|r=c), \text{ если } r=c
  \end{aligned}
\right.
$$
