---
title: "Введение в базы данных"
author: "Иван Савин"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Введание в базовые операции SQL
## 1.1 Термины и определения
### 1.1.3 
Из этого курса мы узнаем, как работае база данных, как спроектировать базу данных. Так же получим некие практические навыки работы с реляционными БД.

Для кого этот курс:
* Узнать об одном из наиболее популярных способов **персистентного** (длительного) хранения данных
* Что-то слышали или сталкивались с базами данных, но знания не **систематизированы**
* Хотели бы сменить профиль деятельности, стать **аналитиком**, **разработчиком**, системным администратором БД
* Хотите попробовать работу с БД, чтобы понять , интересно ли вам

### 1.1.4 План курса
1. **Базовые операции SQL** -- как стать на "ты" с базами данных
2. **Основы реляцилнных СУБД** -- как написать запрос любой сложности; составление более сложных запросов с использованием нескольких сужностей, выборке из нескольких таблиц
3. **Проектирование БД** -- от концепции до физической структуры; все этапы, начиная от концепций и заканчивая физическим воплощением
4. **Использование ORM** -- связь БД с концепциями ООП
5. **Администрирование MySQL и оптимизация запросов** - как стать системным администратором БД
6. **Нереляционные СУБД** -- когда и как сказать *"Not Only SQL"*

#### Технологии и инструменты
##### СУБД:

* **MySQL** -- доминирующая РСУБД среди свободного ПО
* **MongoDB** -- наиболее популярная документоориентированная СУБД; движок для проектирования баз с не четкой или часто меняющейся схемой
* **Redis** -- наиболее стабильная СУБД типа "ключ-значение"; основное преимущество - быстрый доступ к данным

##### Проектирование:

* **MySQL Workbench** -- популярный и свободный инструмент выполнения запросов и проектирования БД
* **Ваш любимый ORM** (*наш* - Django ORM)  -- на любом популярном языке есть несколько вариантов

### 1.1.5 Основные понятия БД

* **Сущность** (Entity) -- класс, хранящийся в базе данных, таблица
* **Объект**(Object)  -- экземпляр сущности
* **Атрибут** (Attribute) -- свойства, характеризуюшие сущность, название столбца в таблице
* **Кортеж** (Tuple) -- строка в таблице, набор значений конкретных атрибутов
* **Домен** (Data domain) -- набор допустимых значений атрибута
* **ИДентификатор** (ID, Identifier) -- атрибут с уникальным значением для данной таблицы

### 1.1.6 Области применения БД

* **Банки, картотеки, любые крупные системы**, в которых нужно хранить и изменять данные, а также иметь доступ к ним с разными ролями (системы, где уже не обойтись *xls-файликом*). Файловая система - иерархическая БД, ее можеет не хватить.
* **Веб-сайты** -- сервер испольует БД для удобства управления информацией и взаимодействия с пользователем.
* **Приложения (мобильные и десктопные)** используют локальные базы для удобства хранения данных по некоторым правилам,
* **Любой программный продукт**, подразумевающий отделение бизнес-логики и уровня хранения данных

### 1.1.7 Архитектура Системы Управления Базой Данных
#### Основные компоненты

* **Ядро** -- оперирование процессами, сеть, взаимодействие с памятью, файловая система и т.д.
* **Диспетчер данных** -- транзакции, кэш, проверка доступа к данным
* **Диспетчер запросов** (*самый важный!*) -- парсер (он проверяет валидность запросов), оптимизатор запросов , исполнитель
* **Набор инструментов для служебных операций** -- резервное копирование, восстановление, мониторинг

### 1.1.8 Характеристики СУБД
#### Преимужества

* Простая схема данных для полльзователья
* Логическая и физическая независимость от данных
* Целостность и защищенность данных 
* Методологический подход к проктированию

#### Недостатки

* Относительная низкая скорость доступа к данным
* Не универсальное решение для любой предметной области
* Меньшая гибкость при добавлении своих типов данных и операций
 
### 1.1.9 Язык SQL
**SQL** Structured Query Language -- язык структурированных запросов; наиболее популярный язык используемый в СУБД

#### Диалекты
* Oracle
* MySQL
* PostgreSQL
* MS SQL
* SQLite
* Access

## 1.2 Базовые операции SQL
### 1.2.1 Полезная информация к уроку
В видеоуроках представлены в том числе скринкасты выполнения SQL-запросов в среде MySQL Workbench. Слушатели также могут использовать эту среду в целях обучения. Все тестовые примеры, используемые в уроках, доступны на [GitHub](https://github.com/amyasnov/stepic-db-intro) для ознакомления. Импорт примеров на локальные машины слушателей не является необходимым для выполнения заданий.

#### Важное пояснение
Все запросы в этом и следующем уроке нужно выполнять через браузер (шаги с заданиями). Ничего ставить на свои компьютеры для прохождения заданий не нужно.

При выполнении запросов через браузер следуйте правилам:

* База уже выбрана и дополнительно писать команду **use** не нужно.
* Система принимает один запрос за раз. Если вы хотите попробовать различные запросы, то выполняйте их по одному, но помните, что каждый раз запрос выполняется на изначальных данных.

#### Используемое ПО, установка
##### 1. Сервер  MySQL
В зависимости от используемой платформы (Windows, Linux, MacOS X) используются различные способы установки.

##### MS Windows
Необходимо скачать дистрибутив [отсюда](http://dev.mysql.com/downloads/mysql/5.5.html#downloads).
Запустить скачанный установщик и следовать инструкциям мастера.

##### Linux
Необходимо установить пакет сервера MySQL с помощью пакетного менеджера системы (apt, yum и др.)

##### Mac OS X
Два варианта установки:

* Необходимо установить пакет сервера MySQL с помощью пакетного менеджера brew, MacPorts.
* Необходимо скачать дистрибутив [отсюда](http://dev.mysql.com/downloads/mysql/5.5.html#downloads). Запустить скачанный установщик и следовать инструкциям мастера.

##### 2. Среда MySQL Workbench
Необходимо установить скачанный [отсюда](http://dev.mysql.com/downloads/workbench/) дистрибутив среды. После скачивания необходимо установить среду с помощью мастера установки или пакетного менеджера.

####  Импорт и работа с тестовыми БД
Для того, чтобы использовать тестовые БД необходимо выполнить следующие действия:
1. Клонировать на локальную машину или скачать в виде архива [репозиторий](https://github.com/amyasnov/stepic-db-intro) с примерами
2. Запустить среду MySQL Workbench
3. Создать новое соединение с установленным предварительно сервисом MySQL (для удобства можно использовать пользователя root)
4. Открыть в MySQL Workbench файл модели (например, **billing_simple.mwb**)
5. В меню Database выбрать пункт Forward Engineer, далее следовать по мастеру 
6. При выборе соединения - выбрать соединение, созданное на шаге 3; для добавления тестовых данных в БД выбрать пункт "Generate INSERT statements for tables"; при необходимости выбрать пункты удаления схемы БД и объектов БД; дождаться исполнения сгененированного скрипта, в процессе его выполнения не должно быть ошибок.
7. Закрыть вкладку с моделью.
8. На главной странице среды выбрать двойным кликом созданное на шаге 3 соединение.
9. В списке схем необходимо выбрать двойным щелчком интересующую для текущей работы.
10Создать новую вкладку для выполнения запроса в меню File пункт New Query Tab

В результате этих действий в среде должно быть активным соединение с одной из БД на сервере.

Далее - можно выполнять запросы к БД.


!!! Переписать комменты!!!










#### Используемое ПО, установка